stages:
- build-test-images
- tests
- publish

variables:
  PACKAGE_REGISTRY_PROJECT_ID: "21689940"

build-test-image-3.12:
  stage: build-test-images
  image: docker:20.10.16
  variables:
    PY_VERSION: "3.12"
    IMAGE: "registry.gitlab.com/applipy/applipy_pg/test"
  services:
  - docker:20.10.16-dind
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
  - docker build -f ./tests/Dockerfile --build-arg "PY_VERSION=${PY_VERSION}" --tag "${IMAGE}:${PY_VERSION}" .
  - docker push "${IMAGE}:${PY_VERSION}"
  only:
    refs:
    - master
    changes:
    - tests/Dockerfile


tests-3.12:
  stage: tests
  image: registry.gitlab.com/applipy/applipy_pg/test:3.12
  services:
  - name: docker:20.10.16-dind
    alias: docker_dind
  variables:
    DOCKER_HOST: tcp://docker_dind:2375
    CONTAINERIZED_HOST: docker_dind
  script:
  - pip install '.[dev]'
  - flake8
  - mypy --strict --ignore-missing-imports applipy_pg tests
  - pytest --cov=applipy_pg --cov-report=term-missing
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/

# tests-X.Y:
#   stage: tests
#   image: python:X.Y
#   services:
#   - docker:20.10.16-dind
#   script:
#   - pip install '.[dev]'
#   - flake8
#   - mypy --strict --ignore-missing-imports applipy_pg tests
#   - pytest --cov=applipy_pg --cov-report=term-missing

publish-gitlab:
  stage: publish
  image: python:latest
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: "${CI_JOB_TOKEN}"
    TWINE_REPOSITORY_URL: "https://gitlab.com/api/v4/projects/${PACKAGE_REGISTRY_PROJECT_ID}/packages/pypi"
  script:
  - pip install twine
  - python setup.py sdist bdist_wheel
  - twine upload dist/*
  only:
    refs:
    - master
    changes:
    - applipy_pg/version.py

# publish-pypi:
#   stage: publish
#   image: python:latest
#   variables:
#     TWINE_USERNAME: __token__
#     TWINE_PASSWORD: "${PYPI_TOKEN}"
#   script:
#   - pip install twine
#   - python setup.py sdist bdist_wheel
#   - twine upload dist/*
#   only:
#     refs:
#     - master
#     changes:
#     - applipy_pg/version.py
